### ISSUE TITLE
Too much padding between `rhb-bands`

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-brand#53]
When`rhb-bands` are siblings there is too much padding created.

The current brand site has lot of variation between blocks and content given the ability to add helper classes to adjust the padding values ie `pb-0`.

Do we want to standardize on a certain amount of spacing between `rhb-bands` using a rule such as:

```css
/* Given at screen sizes larger then 768px */
rhb-band {
  padding-block: var(--rh-space-4x, 64px);
}

/* We could set */
rhb-band + rhb-band {
  padding-block-start: 0px !important;
}
```

Rather then try and mimic all the helper classes?
